### ISSUE TITLE
Getting dependencies with "..." adds unnecessary packages

### ISSUE THREAD

**Issue by pkieltyka** [petejkim/goop#24]
Using `...` at the end of a `go get`, will fetch all of the packages under that path. But in some projects this will import unnecessary packages.. for example like, https://github.com/garyburd/go-oauth. Adding that to your Goopfile will try to fetch the "examples" package and add the `appengine` as a dependency, which clear is not a good thing :|

**Comment by pkieltyka** [comment]
fixed with: https://github.com/pkieltyka/goop/commit/c60be07086405b61d77738a1d4eeb1db2fca025a

.. this does change Goop a bit, since it won't just magically grab every dependency under the sun.. but thats a bad thing to do anyways in my opinion..

**Comment by pkieltyka** [comment]
I'd love to get another opinion on this, but I think its best to be explicit about `go get`ing 

is instead for the developer to specify the "..." at the end of a repo definition in the Goopfile themselves instead of this being implied for every entry.

ie. in a Goopfile

```
github.com/garyburd/go-oauth/oauth #sometag
```

vs.

```
github.com/garyburd/go-oauth/oauth... #sometag
```

**Comment by zeeyang** [comment]
+1 for explicit dependency path. I'm having a problem with circular dependency and came across this patch. This doesn't solve dependency conflicts, but the default "grab everything" behavior mades things much worse.

**Comment by pkieltyka** [comment]
Yea goop sucks. Lots of issues and short comings.

**Comment by zeeyang** [comment]
I don't think the ... notation is necessary. I would prefer to have a `goop introspect` command that go through import headers and build the Goopfile. It should give you the precise dependencies and stay close to Go's import conventions.
